<a href="https://colab.research.google.com/github/Dr-Isam-ALJAWARNEH/fds-project-geodevelopers/blob/main/Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Minimum Spanning Tree (MST) for Optimizing Pollution Monitoring Networks**

## **Importing the required libraries**

In [ ]:
%pip install pygeohash

Requirement already satisfied: pygeohash in /usr/local/lib/python3.11/dist-packages (3.0.1)

In [ ]:
import pandas as pd
import geopandas as gpd
import pygeohash as gh
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
from datascience import *
%matplotlib inline
#path_data = '../../../assets/data/'
import matplotlib.pyplot as plt
plt.style.use('fivethirtyeight')
import numpy as np

## **Configuring variables and Importing Files**

In [ ]:
Geohash_percision = 6

In [ ]:
#Create new dataframe table, and import all available Chicago files in the repositry to it.
Chicago = Table().to_df()

for i in range(1,20):
  file_link = 'https://raw.githubusercontent.com/IsamAljawarneh/datasets/refs/heads/master/data/Chicago/AQ_data/chicago_eclipse_data_part_'+str(i)+'.csv'
  Chicago = pd.concat([Chicago, pd.read_csv(file_link,index_col=False)], ignore_index=True)

In [ ]:
Chicago

,City,DeviceId,LocationName,Latitude,Longitude,ReadingDateTimeUTC,PM25,CalibratedPM25,CalibratedO3,CalibratedNO2,CO,Temperature,Humidity,BatteryLevel,PercentBattery,CellSignal
0,Chicago,2002,State & Garfield (SB),41.794921,-87.625857,2021-06-20 00:03:00,5.561094,NaN,NaN,NaN,0.123580,27.383499,55.128479,4.237187,93.964844,-76.0
1,Chicago,2002,State & Garfield (SB),41.794921,-87.625857,2021-06-20 00:08:10,6.633914,NaN,NaN,NaN,0.132103,27.079086,55.059814,4.236094,93.964844,-81.0
2,Chicago,2002,State & Garfield (SB),41.794921,-87.625857,2021-06-20 00:13:20,4.068707,NaN,NaN,NaN,0.131126,27.079086,55.035400,4.236406,93.964844,-80.0
3,Chicago,2002,State & Garfield (SB),41.794921,-87.625857,2021-06-20 00:18:30,6.351702,NaN,NaN,NaN,0.138784,26.945572,54.632568,4.236094,93.863281,-82.0
4,Chicago,2002,State & Garfield (SB),41.794921,-87.625857,2021-06-20 00:23:40,9.574065,NaN,NaN,NaN,0.413070,26.828079,53.907776,4.235938,93.863281,-81.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2461084,Chicago,2129,Lincoln & California (NWB),41.985920,-87.699628,2021-10-03 23:29:48,4.479115,10.72,34.66,12.51,0.413648,22.817307,73.245239,4.176250,89.785156,-62.0
2461085,Chicago,2129,Lincoln & California (NWB),41.985920,-87.699628,2021-10-03 23:34:58,6.322502,14.89,34.71,6.35,0.656208,22.713165,73.222351,4.186875,89.785156,-61.0
2461086,Chicago,2129,Lincoln & California (NWB),41.985920,-87.699628,2021-10-03 23:40:08,9.796841,13.51,36.71,2.62,0.336273,22.659760,73.472595,4.186250,89.683594,-60.0
2461087,Chicago,2129,Lincoln & California (NWB),41.985920,-87.699628,2021-10-03 23:45:17,5.173977,11.20,34.33,3.53,0.372924,22.526245,73.468018,4.186250,89.683594,-61.0
2461088,Chicago,2129,Lincoln & California (NWB),41.985920,-87.699628,2021-10-03 23:50:28,6.604176,12.62,36.65,11.24,0.345182,22.526245,73.498535,4.185937,89.683594,-61.0

## **Exploring & Working with the Data**

In [ ]:
#Add Geohash grouping based on the latitude and longtiude columns
Chicago["GeoHash Code"] = Chicago.apply(lambda x: gh.encode(x.Latitude, x.Longitude, precision= Geohash_percision), axis=1)

In [ ]:
Chicago

,City,DeviceId,LocationName,Latitude,Longitude,ReadingDateTimeUTC,PM25,CalibratedPM25,CalibratedO3,CalibratedNO2,CO,Temperature,Humidity,BatteryLevel,PercentBattery,CellSignal,GeoHash Code
0,Chicago,2002,State & Garfield (SB),41.794921,-87.625857,2021-06-20 00:03:00,5.561094,NaN,NaN,NaN,0.123580,27.383499,55.128479,4.237187,93.964844,-76.0,dp3ty0
1,Chicago,2002,State & Garfield (SB),41.794921,-87.625857,2021-06-20 00:08:10,6.633914,NaN,NaN,NaN,0.132103,27.079086,55.059814,4.236094,93.964844,-81.0,dp3ty0
2,Chicago,2002,State & Garfield (SB),41.794921,-87.625857,2021-06-20 00:13:20,4.068707,NaN,NaN,NaN,0.131126,27.079086,55.035400,4.236406,93.964844,-80.0,dp3ty0
3,Chicago,2002,State & Garfield (SB),41.794921,-87.625857,2021-06-20 00:18:30,6.351702,NaN,NaN,NaN,0.138784,26.945572,54.632568,4.236094,93.863281,-82.0,dp3ty0
4,Chicago,2002,State & Garfield (SB),41.794921,-87.625857,2021-06-20 00:23:40,9.574065,NaN,NaN,NaN,0.413070,26.828079,53.907776,4.235938,93.863281,-81.0,dp3ty0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2461084,Chicago,2129,Lincoln & California (NWB),41.985920,-87.699628,2021-10-03 23:29:48,4.479115,10.72,34.66,12.51,0.413648,22.817307,73.245239,4.176250,89.785156,-62.0,dp3wu7
2461085,Chicago,2129,Lincoln & California (NWB),41.985920,-87.699628,2021-10-03 23:34:58,6.322502,14.89,34.71,6.35,0.656208,22.713165,73.222351,4.186875,89.785156,-61.0,dp3wu7
2461086,Chicago,2129,Lincoln & California (NWB),41.985920,-87.699628,2021-10-03 23:40:08,9.796841,13.51,36.71,2.62,0.336273,22.659760,73.472595,4.186250,89.683594,-60.0,dp3wu7
2461087,Chicago,2129,Lincoln & California (NWB),41.985920,-87.699628,2021-10-03 23:45:17,5.173977,11.20,34.33,3.53,0.372924,22.526245,73.468018,4.186250,89.683594,-61.0,dp3wu7
2461088,Chicago,2129,Lincoln & California (NWB),41.985920,-87.699628,2021-10-03 23:50:28,6.604176,12.62,36.65,11.24,0.345182,22.526245,73.498535,4.185937,89.683594,-61.0,dp3wu7

In [ ]:
Chicago2 = Table().from_df(Chicago)

In [ ]:
Chicago2

City    | DeviceId | LocationName          | Latitude | Longitude | ReadingDateTimeUTC  | PM25    | CalibratedPM25 | CalibratedO3 | CalibratedNO2 | CO       | Temperature | Humidity | BatteryLevel | PercentBattery | CellSignal | GeoHash Code
Chicago | 2002     | State & Garfield (SB) | 41.7949  | -87.6259  | 2021-06-20 00:03:00 | 5.56109 | nan            | nan          | nan           | 0.12358  | 27.3835     | 55.1285  | 4.23719      | 93.9648        | -76        | dp3ty0
Chicago | 2002     | State & Garfield (SB) | 41.7949  | -87.6259  | 2021-06-20 00:08:10 | 6.63391 | nan            | nan          | nan           | 0.132103 | 27.0791     | 55.0598  | 4.23609      | 93.9648        | -81        | dp3ty0
Chicago | 2002     | State & Garfield (SB) | 41.7949  | -87.6259  | 2021-06-20 00:13:20 | 4.06871 | nan            | nan          | nan           | 0.131126 | 27.0791     | 55.0354  | 4.23641      | 93.9648        | -80        | dp3ty0
Chicago | 2002     | State & Garfield (SB) | 41.7949  | -87.6259  | 2021-06-20 00:18:30 | 6.3517  | nan            | nan          | nan           | 0.138784 | 26.9456     | 54.6326  | 4.23609      | 93.8633        | -82        | dp3ty0
Chicago | 2002     | State & Garfield (SB) | 41.7949  | -87.6259  | 2021-06-20 00:23:40 | 9.57407 | nan            | nan          | nan           | 0.41307  | 26.8281     | 53.9078  | 4.23594      | 93.8633        | -81        | dp3ty0
Chicago | 2002     | State & Garfield (SB) | 41.7949  | -87.6259  | 2021-06-20 00:28:50 | 6.02794 | nan            | nan          | nan           | 0.157761 | 26.7667     | 58.0338  | 4.23609      | 93.8633        | -82        | dp3ty0
Chicago | 2002     | State & Garfield (SB) | 41.7949  | -87.6259  | 2021-06-20 00:34:00 | 3.61224 | nan            | nan          | nan           | 0.115831 | 26.3367     | 56.1356  | 4.23625      | 93.8633        | -81        | dp3ty0
Chicago | 2002     | State & Garfield (SB) | 41.7949  | -87.6259  | 2021-06-20 00:39:10 | 3.75591 | nan            | nan          | nan           | 0.122269 | 26.2032     | 55.838   | 4.22625      | 93.8633        | -81        | dp3ty0
Chicago | 2002     | State & Garfield (SB) | 41.7949  | -87.6259  | 2021-06-20 00:44:20 | 6.00689 | nan            | nan          | nan           | 0.184926 | 26.1712     | 55.6427  | 4.23547      | 93.8633        | -80        | dp3ty0
Chicago | 2002     | State & Garfield (SB) | 41.7949  | -87.6259  | 2021-06-20 00:49:30 | 8.50949 | nan            | nan          | nan           | 0.11234  | 26.2032     | 55.4581  | 4.23609      | 93.8633        | -80        | dp3ty0
... (2461079 rows omitted)

In [ ]:
Chicago3 = Chicago2.where("DeviceId", 2002)
Chicago3

City    | DeviceId | LocationName          | Latitude | Longitude | ReadingDateTimeUTC  | PM25    | CalibratedPM25 | CalibratedO3 | CalibratedNO2 | CO       | Temperature | Humidity | BatteryLevel | PercentBattery | CellSignal | GeoHash Code
Chicago | 2002     | State & Garfield (SB) | 41.7949  | -87.6259  | 2021-06-20 00:03:00 | 5.56109 | nan            | nan          | nan           | 0.12358  | 27.3835     | 55.1285  | 4.23719      | 93.9648        | -76        | dp3ty0
Chicago | 2002     | State & Garfield (SB) | 41.7949  | -87.6259  | 2021-06-20 00:08:10 | 6.63391 | nan            | nan          | nan           | 0.132103 | 27.0791     | 55.0598  | 4.23609      | 93.9648        | -81        | dp3ty0
Chicago | 2002     | State & Garfield (SB) | 41.7949  | -87.6259  | 2021-06-20 00:13:20 | 4.06871 | nan            | nan          | nan           | 0.131126 | 27.0791     | 55.0354  | 4.23641      | 93.9648        | -80        | dp3ty0
Chicago | 2002     | State & Garfield (SB) | 41.7949  | -87.6259  | 2021-06-20 00:18:30 | 6.3517  | nan            | nan          | nan           | 0.138784 | 26.9456     | 54.6326  | 4.23609      | 93.8633        | -82        | dp3ty0
Chicago | 2002     | State & Garfield (SB) | 41.7949  | -87.6259  | 2021-06-20 00:23:40 | 9.57407 | nan            | nan          | nan           | 0.41307  | 26.8281     | 53.9078  | 4.23594      | 93.8633        | -81        | dp3ty0
Chicago | 2002     | State & Garfield (SB) | 41.7949  | -87.6259  | 2021-06-20 00:28:50 | 6.02794 | nan            | nan          | nan           | 0.157761 | 26.7667     | 58.0338  | 4.23609      | 93.8633        | -82        | dp3ty0
Chicago | 2002     | State & Garfield (SB) | 41.7949  | -87.6259  | 2021-06-20 00:34:00 | 3.61224 | nan            | nan          | nan           | 0.115831 | 26.3367     | 56.1356  | 4.23625      | 93.8633        | -81        | dp3ty0
Chicago | 2002     | State & Garfield (SB) | 41.7949  | -87.6259  | 2021-06-20 00:39:10 | 3.75591 | nan            | nan          | nan           | 0.122269 | 26.2032     | 55.838   | 4.22625      | 93.8633        | -81        | dp3ty0
Chicago | 2002     | State & Garfield (SB) | 41.7949  | -87.6259  | 2021-06-20 00:44:20 | 6.00689 | nan            | nan          | nan           | 0.184926 | 26.1712     | 55.6427  | 4.23547      | 93.8633        | -80        | dp3ty0
Chicago | 2002     | State & Garfield (SB) | 41.7949  | -87.6259  | 2021-06-20 00:49:30 | 8.50949 | nan            | nan          | nan           | 0.11234  | 26.2032     | 55.4581  | 4.23609      | 93.8633        | -80        | dp3ty0
... (30802 rows omitted)

In [ ]:
Chicago3.group(["DeviceId", "GeoHash Code"])

DeviceId | GeoHash Code | count
2002     | dp3ty0       | 30812

In [ ]:
#Create new dataframe table, and import all available Chicago files in the repositry to it.
Chicago4 = Table().to_df()
Chicago5 = Table().to_df()
for i in range(1,20):
  file_link = 'https://raw.githubusercontent.com/IsamAljawarneh/datasets/refs/heads/master/data/Chicago/AQ_data/chicago_eclipse_data_part_'+str(i)+'.csv'
  Chicago4 = pd.read_csv(file_link,index_col=False)
  Chicago4["GeoHash Code"] = Chicago4.apply(lambda x: gh.encode(x.Latitude, x.Longitude, precision= Geohash_percision), axis=1)
  Chicago5 = pd.concat([Chicago5, (Table().from_df(Chicago4).group(["DeviceId", "GeoHash Code"])).to_df()], ignore_index=True)

In [ ]:
Chicago5

      DeviceId GeoHash Code  count
0         2002       dp3ty0   5824
1         2003       dp3ty0   5747
2         2004       dp3wh3   5839
3         2005       dp3wh6   5847
4         2006       dp3wh6   5841
...        ...          ...    ...
1396      2123       dp3tsg   1914
1397      2124       dp3tmt   1950
1398      2125       dp3tus   1947
1399      2127       dp3tem   1939
1400      2129       dp3wu7    277

[1401 rows x 3 columns]

In [ ]:
Chicago6 = Table().from_df(Chicago5).sort("DeviceId")
Chicago6

DeviceId | GeoHash Code | count
2002     | dp3ty0       | 5824
2002     | dp3ty0       | 1929
2002     | dp3ty0       | 1939
2002     | dp3ty0       | 1938
2002     | dp3ty0       | 1946
2002     | dp3ty0       | 1929
2002     | dp3ty0       | 1947
2002     | dp3ty0       | 1944
2002     | dp3ty0       | 1924
2002     | dp3ty0       | 1950
... (1391 rows omitted)

In [ ]:
Chicago7 = Chicago6.group(["DeviceId", "GeoHash Code"], collect=sum)
Chicago7

DeviceId | GeoHash Code | count sum
2002     | dp3ty0       | 30812
2003     | dp3ty0       | 30865
2004     | dp3wh3       | 31155
2005     | dp3wh6       | 31090
2006     | dp3wh6       | 31090
2008     | dp3ts0       | 31097
2009     | dp3w7v       | 31145
2010     | dp3w7v       | 31071
2012     | dp3wk6       | 31137
2013     | dp3t59       | 31130
... (111 rows omitted)

In [ ]:
Chicago8 = Chicago7.group("DeviceId")
Chicago8.sort("count", descending=True)

DeviceId | count
2002     | 1
2003     | 1
2004     | 1
2005     | 1
2006     | 1
2008     | 1
2009     | 1
2010     | 1
2012     | 1
2013     | 1
... (111 rows omitted)

In [ ]:
Chicago9 = Chicago7.group("GeoHash Code")
Chicago9.sort("count", descending=True)

GeoHash Code | count
dp3t59       | 3
dp3ts0       | 3
dp3w55       | 3
dp3w7v       | 3
dp3tus       | 2
dp3twj       | 2
dp3ty0       | 2
dp3w59       | 2
dp3wh6       | 2
dp3wn4       | 2
... (96 rows omitted)

In [ ]:
Chicago7.where("GeoHash Code", "dp3t59")

DeviceId | GeoHash Code | count sum
2013     | dp3t59       | 31130
2014     | dp3t59       | 31087
2144     | dp3t59       | 21994